version: '3.8'

services:
  y-provider:
    container_name: y-provider
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"  # expose the YJS WebSocket server
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    user: "${DOCKER_USER:-1000:1000}"  # safe default if not passed
